In [5]:
import pandas as pd
import numpy as np


Preprocess

In [49]:
dfproducts = pd.read_csv("products.csv", sep=",")
dforders = pd.read_csv("orders.csv", sep=",")
dfcustomers = pd.read_csv("customers.csv", sep=",")




Creates combo table list of the most popular combinations

In [15]:
combinationtable = np.zeros((len(dfproducts),len(dfproducts)))

orderpercustomerid = {}
print((len(dfproducts)))
print(combinationtable.shape)
combolist = []
currentnumset = set()
prevorderid = ""
for index,row in dforders.iterrows():
  currentorderid = row["OrderID"]
  if currentorderid != prevorderid:
    prevorderid = currentorderid
    combolist.append(currentnumset)
    currentnumset = set()
  currentnumset.add(int(row["ProductID"][1:]))

for currentset in combolist:
  currentlist = list(currentset)
  i = 0
  j = 0
  while i < len(currentlist):
    j=i+1
    while j < len(currentlist):
      combinationtable[currentlist[i],currentlist[j]]+=1
      combinationtable[currentlist[j],currentlist[i]]+=1

      j+=1
    i+=1

print(combinationtable)





100
(100, 100)
[[0. 3. 3. ... 4. 1. 1.]
 [3. 0. 2. ... 3. 8. 4.]
 [3. 2. 0. ... 0. 5. 3.]
 ...
 [4. 3. 0. ... 0. 1. 4.]
 [1. 8. 5. ... 1. 0. 2.]
 [1. 4. 3. ... 4. 2. 0.]]


les items d'une transaction ensemble, dans une nouvelle table "composed_transactions"


In [47]:
combinationtable = np.zeros((len(dfproducts),len(dfproducts)))

orderpercustomerid = {}
print((len(dfproducts)))
print(combinationtable.shape)
combohash = {}
currentnumset = set()
prevorderid = ""
for index,row in dforders.iterrows():

  currentorderid = row["OrderID"]
  if currentorderid not in combohash:

    combohash[currentorderid] = set()
  combohash[currentorderid].add(row["ProductID"][1:])

print(combohash)

100
(100, 100)
{'O000': {'038'}, 'O001': {'079'}, 'O002': {'018', '042', '074', '083'}, 'O003': {'090', '003'}, 'O004': {'060'}, 'O005': {'011', '053', '018', '061'}, 'O006': {'022', '010', '094', '099'}, 'O007': {'003', '099'}, 'O008': {'032', '062'}, 'O009': {'031', '016', '027'}, 'O010': {'021', '069', '062', '074'}, 'O011': {'022', '086', '019', '094'}, 'O012': {'087', '039', '015'}, 'O013': {'006', '020', '067'}, 'O014': {'097', '053', '001'}, 'O015': {'045', '001'}, 'O016': {'011', '085'}, 'O017': {'015', '055', '044', '079'}, 'O018': {'024', '074'}, 'O019': {'029', '012', '080'}, 'O020': {'012', '086', '033', '008'}, 'O021': {'058', '032', '059'}, 'O022': {'028', '067', '042'}, 'O023': {'022', '002'}, 'O024': {'025'}, 'O025': {'090', '085', '091'}, 'O026': {'016'}, 'O027': {'030'}, 'O028': {'015', '050', '007', '089'}, 'O029': {'047', '000'}, 'O030': {'069', '010'}, 'O031': {'069', '023'}, 'O032': {'073', '048', '001', '081'}, 'O033': {'033'}, 'O034': {'072', '009', '068', '078'

Name is key, purchase popularity value

In [45]:
customernamelist = dfcustomers['CustomerName'].tolist()
print(customernamelist)

nameidhash = {}

for index,row in dfcustomers.iterrows():
  name = row["CustomerName"]
  if name == name:
    if name.split(" ")[0] != "Mr.":
      hashname = name.split(" ")[0]
    else:
      hashname = name.split(" ")[1]

    if int(row["CustomerID"][1:]) not in nameidhash:
      nameidhash[int(row["CustomerID"][1:])] = set()
    nameidhash[int(row["CustomerID"][1:])] = hashname



nameproductpopularityhash = {}
for index,row in dforders.iterrows():
  ProductID = int(row["ProductID"][1:])
  CustomerID = int(row["CustomerID"][1:])
  try:
    if nameidhash[CustomerID] not in nameproductpopularityhash:
      nameproductpopularityhash[nameidhash[CustomerID]] = np.zeros(len(dfproducts))
    nameproductpopularityhash[nameidhash[CustomerID]][ProductID]+=1
  except:
    # print(f"CustomerID {CustomerID} has no name")
    i = 0

print(nameproductpopularityhash)





[nan, 'Kevin Griffin', 'Lisa Smith', 'Nicholas Roberts', nan, 'Connie Harrison', 'Steven Mooney', 'Dean Adams', 'Brian Jones', nan, 'Thomas Hernandez', 'Erik Salas', 'Alexandria Jimenez', 'Tonya Fuentes', 'Karen Fox', 'Michael Larsen', 'Tamara Moore', 'Michael Dodson', 'Michael Hansen', 'Juan Neal', nan, 'Danielle Carr', 'David Owen', 'Christian Allen', 'Justin Webb', 'John Wilson', 'Robert Lewis', 'Angela Jackson', 'Gina Acosta', nan, 'Katherine Norton', 'Dominic Wilson', 'Amy Davis', 'Nicholas Marshall', 'Victoria Carter', 'Theresa Day', 'Robert Jefferson', 'Jack Brown', 'Tamara Mcneil', 'Rachel Wilkerson', 'Katrina Bell', 'Timothy Smith', 'Russell Koch', 'Linda Hines', 'Kelsey Reid', 'Brett Price', 'Nathan Burns', 'Jeffrey Wade', nan, 'Tina Brown', 'Tanner Turner', 'Kimberly Sanchez', 'Matthew Stevens', 'Becky Torres', 'Travis Gallagher', 'Rebecca Anderson', 'Suzanne Carter', 'Timothy Scott', 'Hannah King', 'Samantha Compton', 'Matthew Werner', 'April Martin', 'Joshua Powell', 'Mary

Popularity by region

In [50]:
customernamelist = dfcustomers['CustomerName'].tolist()
print(customernamelist)

regionidhash = {}

for index,row in dfcustomers.iterrows():
  name = row["Location"]
  if name == name:
    if int(row["CustomerID"][1:]) not in nameidhash:
      nameidhash[int(row["CustomerID"][1:])] = set()
    nameidhash[int(row["CustomerID"][1:])] = name



nameproductpopularityhash = {}
for index,row in dforders.iterrows():
  ProductID = int(row["ProductID"][1:])
  CustomerID = int(row["CustomerID"][1:])
  try:
    if nameidhash[CustomerID] not in nameproductpopularityhash:
      nameproductpopularityhash[nameidhash[CustomerID]] = np.zeros(len(dfproducts))
    nameproductpopularityhash[nameidhash[CustomerID]][ProductID]+=1
  except:
    # print(f"CustomerID {CustomerID} has no name")
    i = 0

print(nameproductpopularityhash)





[nan, 'Kevin Griffin', 'Lisa Smith', 'Nicholas Roberts', nan, 'Connie Harrison', 'Steven Mooney', 'Dean Adams', 'Brian Jones', nan, 'Thomas Hernandez', 'Erik Salas', 'Alexandria Jimenez', 'Tonya Fuentes', 'Karen Fox', 'Michael Larsen', 'Tamara Moore', 'Michael Dodson', 'Michael Hansen', 'Juan Neal', nan, 'Danielle Carr', 'David Owen', 'Christian Allen', 'Justin Webb', 'John Wilson', 'Robert Lewis', 'Angela Jackson', 'Gina Acosta', nan, 'Katherine Norton', 'Dominic Wilson', 'Amy Davis', 'Nicholas Marshall', 'Victoria Carter', 'Theresa Day', 'Robert Jefferson', 'Jack Brown', 'Tamara Mcneil', 'Rachel Wilkerson', 'Katrina Bell', 'Timothy Smith', 'Russell Koch', 'Linda Hines', 'Kelsey Reid', 'Brett Price', 'Nathan Burns', 'Jeffrey Wade', nan, 'Tina Brown', 'Tanner Turner', 'Kimberly Sanchez', 'Matthew Stevens', 'Becky Torres', 'Travis Gallagher', 'Rebecca Anderson', 'Suzanne Carter', 'Timothy Scott', 'Hannah King', 'Samantha Compton', 'Matthew Werner', 'April Martin', 'Joshua Powell', 'Mary